#!/usr/bin/env bash
set -euo pipefail
OUT="SKILLS-TODO.md"
STRICT=0
for arg in "$@"; do
  case "$arg" in
    --strict) STRICT=1 ;;
    --output=*) OUT="${arg#--output=}" ;;
  esac
done
echo "# Skills audit" > "$OUT"
echo "" >> "$OUT"
echo "Generated by scripts/audit-skills.sh." >> "$OUT"
echo "" >> "$OUT"
echo "No destructive changes are performed by this audit." >> "$OUT"
echo "" >> "$OUT"
echo "## Duplicate candidates" >> "$OUT"
dupes=0
if [[ -d skills ]]; then
  while IFS= read -r -d '' f; do
    base=$(basename "$f")
    count=$(find skills -type f -name "$base" | wc -l)
    if (( count > 1 )); then
      printf -- "- %s (%s copies)\n" "$base" "$count" >> "$OUT"
      dupes=1
    fi
  done < <(find skills -type f -print0 | sort -z -u)
fi
if (( dupes == 0 )); then
  echo "- duplicates: none detected" >> "$OUT"
fi
if (( STRICT == 1 && dupes == 1 )); then
  echo "SKILLS-AUDIT: duplicates found" >&2
  exit 1
fi
echo "SKILLS-AUDIT: complete"
